name: "Compile kernel"

on:
  workflow_dispatch:
    inputs:
      AUTHOR:
        description: 'AUTHOR'
        required: true
        default: 'Veynamer'   
      CHECKOUT_REPO:
        description: 'CHECKOUT_REPO'
        required: true
        default: 'android_kernel_xiaomi_mt6765'
      CHECKOUT_BRANCH:
        description: 'CHECKOUT_BRANCH'
        required: true
        default: 'alps-0.6'
      USEDEFCONFIG:
        description: 'USEDEFCONFIG'
        required: true
        default: 'certus_defconfig'

env:
  CLANG_VER: 'proton-clang'
  ARCHOSUB: 'arm64'
  KERNEL_DIR: 'kernel_source'
  COMPILE_THREAD: '32' # $(nproc --all) cpu核心数

jobs:
  kernel:
    name: Compile kernel
    runs-on: ubuntu-latest
    steps:
    - name: cacheClang
      id: cacheClang
      uses: actions/cache@v2
      with:
        path: |
          ${{ github.workspace }}/${{ env.CLANG_VER }}
        key: ${{ runner.os }}/${{ env.CLANG_VER }}

    - name: Get time
      id: get_time
      run: |
        echo "actions_time=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.AUTHOR }}/${{ github.event.inputs.CHECKOUT_REPO }}
        ref: ${{ github.event.inputs.CHECKOUT_BRANCH }}
        path: ${{ env.KERNEL_DIR }}

    - name: Check out the compiler
      if: steps.cacheClang.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: kdrag0n/proton-clang
        path: ${{ env.CLANG_VER }}

    - name: Pull template
      uses: actions/checkout@v3
      with:
        path: Anykernel

    - name: Prepare the compilation environment
      run: |
        sudo apt update -y
        sudo apt install -y git wget unzip p7zip-full git

    - name: Compiling
      run: |
        cd ${{ github.workspace }}/${{ env.KERNEL_DIR}}
        export ARCH=${{ env.ARCHOSUB}}
        export AR=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/llvm-ar
        export NM=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/llvm-nm
        export OBJCOPY=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/llvm-objcopy
        export OBJDUMP=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/llvm-objdump
        export STRIP=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/llvm-strip
        export SUBARCH=${{ env.ARCHOSUB}}
        export CC=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/clang
        export CROSS_COMPILE=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/arm-linux-gnueabi-
        export PATH="${{ github.workspace }}/${{ env.CLANG_VER }}/bin:$PATH"

        make O=out ${{ github.event.inputs.USEDEFCONFIG }}

        make -j${{ env.COMPILE_THREAD }} O=out \
        AR=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/llvm-ar \
        NM=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/llvm-nm \
        OBJCOPY=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/llvm-objcopy \
        OBJDUMP=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/llvm-objdump \
        STRIP=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/llvm-strip \
        ARCH=${{ env.ARCHOSUB}} \
        SUBARCH=${{ env.ARCHOSUB}} \
        CC=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/clang \
        CROSS_COMPILE=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=${{ github.workspace }}/${{ env.CLANG_VER }}/bin/arm-linux-gnueabi- \
        ${{ github.event.inputs.COMPILE_SET }}

    - name: Packaged kernel
      run: |
        cd ${{ github.workspace }}/Anykernel
        cp ${{ github.workspace }}/${{ env.KERNEL_DIR}}/out/arch/arm64/boot/Image.gz-dtb ${{ github.workspace }}/Anykernel/
        zip -u Kernel_template.zip Image.gz-dtb
        cd ${{ github.workspace }}
        mkdir kernel_public
        cp ${{ github.workspace }}/Anykernel/Kernel_template.zip ${{ github.workspace }}/kernel_public/${{ env.actions_time }}.zip
    
    - name: Publish to Release
      if: github.event.inputs.USE_LANZOU == '0'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: Release ${{ github.event.inputs.AUTHOR }}/${{ github.event.inputs.CHECKOUT_REPO }}-${{ env.actions_time }}
        files: |
          ${{ github.workspace }}/kernel_public/${{ env.actions_time }}.zip
    
